# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 06:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='hobby',
            new_name='question_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='student_name',
        ),
    ]
