# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='theater_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
