# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_theater_theater_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moivetimetable',
            name='movie_info',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='theater',
        ),
        migrations.AddField(
            model_name='moivetimetable',
            name='theater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Theater'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.MoiveTimeTable'),
        ),
    ]
