# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170613_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=50)),
                ('stroe_loc', models.CharField(max_length=50)),
                ('store_time', models.CharField(max_length=10)),
                ('store_info', models.CharField(max_length=300)),
                ('store_img', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_info',
        ),
        migrations.AddField(
            model_name='moivetimetable',
            name='movie_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Movie'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_thum_loc',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
