# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170614_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_info',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_n',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
