# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170614_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='theater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Theater'),
        ),
    ]
