# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_store_theater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_img',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
