# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170614_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_cata',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_info',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
