# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170614_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moivetimetable',
            name='movie_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='moivetimetable',
            name='movie_loc',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='moivetimetable',
            name='movie_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='moivetimetable',
            name='movie_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_actor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_director',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_n',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='store',
            name='stroe_loc',
            field=models.CharField(max_length=100),
        ),
    ]
